# Generated by Django 3.2.9 on 2021-11-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacol', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_datapo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metric_view_control',
                'managed': False,
            },
        ),
    ]
