# Generated by Django 3.2.9 on 2021-11-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacol', '0004_metrics_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metrics_view',
            table='metric_view_home_checkvacc',
        ),
    ]
